name: Publish levell postgres docker image

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push levell postgres docker images to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push levell postgres docker
        uses: docker/build-push-action@v2
        with:
          push: true
          target: levell-postgres-deploy
          tags: |
            ghcr.io/jimmylevell/postgres/levell_postgres:latest
      -
        name: Build and push levell pgadmin docker
        uses: docker/build-push-action@v2
        with:
          push: true
          target: levell-pgadmin-deploy
          tags: |
            ghcr.io/jimmylevell/postgres/levell_pgadmin:latest
      -
        name: Deploy to swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: docker@levell.ch
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          pull_images_first: true
          deploy_path: /home/docker/levell/postgres
          stack_file_name: docker-compose.prod.yml
          args: --with-registry-auth --prune postgres
